version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DEBUG: "1"
      SECRET_KEY: your_development_secret_key
      DATABASE_URL: "mysql://root:password@db:3306/mydb"
      REDIS_URL: "redis://redis:6379/0"
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    container_name: mysql_dev
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:6.0
    container_name: redis_dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
