version: '3.8'

services:
  web:
    build:
      context: .
    image: myproject:latest
    restart: always
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: myproject.settings.production
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}
      DEBUG: "False"
    healthcheck:
      test: ["CMD", "python", "nginx/healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - nginx
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    restart: always

volumes:
  static_volume:
  media_volume:
